language: node_js
os: linux
node_js:
  - "10"
jobs:
  include:
    - stage: testing
    - stage: npm release
      if: branch = master
      before_deploy:
        - npm run build
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: true
