language: node_js
os: linux
node_js:
  - "10"
jobs:
  include:
    - stage: testing
    - stage: npm release
      before_deploy:
        - npm run build
      deploy:
        on:
          all_branches: true
          condition: ${TRAVIS_BRANCH} =~ ^release\/.*$
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_token: "$NPM_TOKEN"
        cleanup: false
